services:
  generator:
    container_name: ct-to-terraform
    image: node:24.3-alpine
    working_dir: /usr/app
    command: npm i commercetools-terraform-generator
    volumes:
      - ./:/usr/app
      - ./${OUTPUT_DIR}:/terraform
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    working_dir: /terraform
    command: init
    volumes:
    - ./${OUTPUT_DIR}:/terraform
    depends_on: 
      - generator